<?php

/*
 * LMS version 1.11-git
 *
 *  (C) Copyright 2001-2013 LMS Developers
 *
 *  Please, see the doc/AUTHORS for more information about authors!
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License Version 2 as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 *  USA.
 *
 *  $Id$
 */

$_LANG['Balance Sheet:'] = 'Bilans finansowy:';
$_LANG['Customer Information'] = 'Informacje o kliencie';
$_LANG['Name/Surname:'] = 'Nazwa/Nazwisko:';
$_LANG['Generated by LMS $a'] = 'Wygenerowano przy użyciu LMS $a';
$_LANG['Monthly payments:'] = 'Miesięczne opłaty:';
$_LANG['No such operations.'] = 'Brak operacji.';
$_LANG['Your IP address was not recognized by system. Please to ensure that you are using computer connected to our network, and you are not using proxy servers. Information about your balance are accessible only from registered computer.'] = 'Państwa adres IP nie został rozpoznany przez system. Proszę się upewnić, że korzystacie Państwo z komputera podłaczonego do naszej sieci i czy nie korzystacie z serwera proxy. Informacje o Państwa bilansie są dostępne tylko z zarejestrowanego komputera.';
